### ISSUE TITLE
Missing test.h5 model 

### ISSUE THREAD

**Issue by kesmitopiwala** [Shantanu66/API-for-Reality-Conjurer#1]
Please add test.h5 model so we will be able to run

**Comment by Shantanu66** [comment]
@kesmitopiwala You can now download the trained model file.I have added a download link in the readme as the file is quite big for github you can then follow the steps specified below and run the app.Sorry for the inconvinience.

**Comment by kesmitopiwala** [comment]
Thanks for your response, but this link is not working @Shantanu66
